### ISSUE TITLE
autocomplete over-rides and excludes user input if there's a partial match

### ISSUE THREAD

**Issue by nkmeyers** [vecnet/dl-discovery#112]
If I try to search for "The dominant Anopheles vectors "  autocomplete over-rides my search terms and I can't delete or pare back what it overwrites so I can't get all the title matches I need/expect when a phrase matches more than one title  . . .

**Comment by dbrower** [comment]
the problem is the colors of the ghosted text and the typed-in text are very close to each other, so the ghost text looks like typed in text. I disabled the ghosting of the text, so any matches require selection from the drop down list.

deployed.
