### ISSUE TITLE
Need to update license pull down options to v 4 

### ISSUE THREAD

**Issue by nkmeyers** [vecnet/dl-discovery#114]
Need to update vecnet digital libraries  license pull-down options they are out of date!  Need options like: "Attribution 4.0 International (CC BY 4.0)" 

I have stuff I've added recently that is licensed as CC BY 4.0 international and ours are older versioned - also i thought there was some license notes field were we could put notes re licensing but I don't see that now . . . we need a spot to put info when the pull down choices are not the license the data provider actually uses/provides?

Natalie

**Comment by dbrower** [comment]
Is it better to display a full title for the licenses, e.g. "Attribution 4.0 International", or to use the shorter version (e.g. "CC BY 4.0")? We are using the full title for the 3.0 versions, but it seems like the shorter version is clearer.

**Comment by nkmeyers** [comment]
I'd use the shorter version - it'd be great to display the license image too but I'm easy on adding that later!

**Comment by dbrower** [comment]
I think this commit in the back end is enough. https://github.com/vecnet/vecnet-dl/commit/c9044f66ecc096b01720dfc7455ac98dc628979c

Still working on it...

**Comment by dbrower** [comment]
This is deployed to production. You can set the license.

BUT, it won't be updated in the discovery interface since the backend is not updating the lastmodified timestamp, which is what the discovery interface is using to figure out what needs to be harvested. I'll look at that next week.

**Comment by dbrower** [comment]
Everything is in production and working. (n.b. the discovery interface polls for item updates every 5 minutes)
