### ISSUE TITLE
Include spatial data when calculating bounding boxes

### ISSUE THREAD

**Issue by dbrower** [vecnet/dl-discovery#13]
The bounding box for items are calculated from the place name data, and does not include any coordinate information which may be present. Include coordinate data.

**Comment by stevenvandervalk** [comment]
@dbrower  Is this still applicable?  Just curious

**Comment by dbrower** [comment]
This is still open. The one hole in the geospatial processing is handling the raw coordinates that people can assign to records. We need to do the following for them:
- Ensure they are exported from the DL (`https://dl.vecnet.org/files/XXXXX.xml`)
- Have the harvester include them in the bounding box calculations
- Specify a solr field for them (I think this is lacking from the solr document because they were _one more thing to think about_)
- Display the coordinates on the item show page in the discovery application.

**Comment by stevenvandervalk** [comment]
Closed until further decision on funding and future.
