### ISSUE TITLE
bounding boxes displaying correctly on front page

### ISSUE THREAD

**Issue by dbrower** [vecnet/dl-discovery#18]
I think the bounding boxes are not displayed correctly on the front page because their coordinates are not being decoded out of the solr fields correctly. Moreover, each solr field concerning a bounding box puts the coordinates in a different order. Specifically,

```
"solr_bbox" is "#{west} #{south} #{east} #{north}"
"solr_geom" is "ENVELOPE(#{west}, #{east}, #{north}, #{south})"
"georss_box_s" is "#{south} #{west} #{north} #{east}"
```

Don't shoot me for this. It comes from solr.

Making this an issue so that it is trackable. I hope it helps with debugging.

**Comment by stevenvandervalk** [comment]
Thanks Don.  I think we are finally approaching a decent approach to this and the meridian issue.

**Comment by stevenvandervalk** [comment]
Ok we've had a crack at it with 2227d674e3f16cae1fabe1bf9113a7fa6151c873 and 5b721307bee709c45d701f866c28482229ed3696. They should be on the deploy vm now.
