### ISSUE TITLE
Migration error when installing -- duplicate column name "email"

### ISSUE THREAD

**Issue by DanielBaird** [vecnet/dl-discovery#2]
Looks like a bad migration?

```
== 20150131013853 AddUidToUser: migrating =====================================
-- change_table(:users)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

SQLite3::SQLException: duplicate column name: email: ALTER TABLE "users" ADD "email" varchar(255)/Users/pvrdwb/jcu/dl-discovery/vendor/gems/sqlite3-1.3.10/lib/sqlite3/database.rb:91:in `initialize'
/
```

**Comment by dbrower** [comment]
The old database used email as a primary key. But it isn't anymore since with pubtkt we use the uid in the ticket. I would recommend just deleting your test/development database and starting from scratch.

This means I messed up the migration. Fortunately there is no production data.

**Comment by DanielBaird** [comment]
I got this migrating up from nothing, it looks like the latest migration is trying to add a new email field when there's been one there since the initial table creation.  So should the email field get removed?  Or just made not-required?

**Comment by dbrower** [comment]
It should be  non required. I can look at his tomorrow morning. Meanwhile you could use do:schema to create the database without running migrations.
