### ISSUE TITLE
The metadata URL field isn't populated from the JSON object in the ruby document

### ISSUE THREAD

**Issue by stevenvandervalk** [vecnet/dl-discovery#28]

**Comment by dbrower** [comment]
Is there a more detailed explanation for this bug? Is this something I could look at?

**Comment by stevenvandervalk** [comment]
No, there is some placeholder code in https://github.com/vecnet/dl-discovery/blob/qa-deploy/app/views/catalog/_upper_metadata.html.erb#L31 that I need to fix and this is that.

**Comment by stevenvandervalk** [comment]
Fixed by f076cf7ef2962ead53cf600d7803708cc57a5b1c
