### ISSUE TITLE
Feedback form should go to mailing list

### ISSUE THREAD

**Issue by dbrower** [vecnet/dl-discovery#38]
We decided this on the call yesterday. I think we meant the MDOC list for the time being. Possible changing to another mailing list after the production deploy. Open question is whether the application can post to the google group.

**Comment by stevenvandervalk** [comment]
The current email is `feedback@vecnet.org` so that can be changed to something else or made to forward. `vecnet@jcu.edu.au` seems to be the current VecNET contact us.  
I think only members can post to Google Groups so not sure if anyone knows how? I can have it email me and I can forward or something work flowed.

**Comment by stevenvandervalk** [comment]
Looks like the original setup was to intended use the vecnet.org domain which uses Zoho email and use their Bug list tracker thing...`https://www.zoho.com/projects/issue-management-software.html`.

So all the sites could use that or/and have it forward to some other issue tracker that you guys use?

**Comment by stevenvandervalk** [comment]
@dbrower I've changed it to `support@vecnet.zohosupport.com` which is similar to support@vecnet.org.  I'm not sure who is receiving these emails/support requests on the VecNET side so let me know if you hear anything :)

But basically when the rest of the sites implement the feedback mailer they should decide where this should go.

**Comment by dbrower** [comment]
Is that a service which vecnet already subscribes to? I want to make sure the emails are not going into a bit bucket no one looks at.

**Comment by stevenvandervalk** [comment]
I was only guessing yes since it was setup.   But nobody has replied to my test feedbacks yet.  
Am happy to change it to another email that works
