### ISSUE TITLE
Type ahead for search box

### ISSUE THREAD

**Issue by dbrower** [vecnet/dl-discovery#42]
Model after the following implementation. It adds some fields to solr as well as a controller and some JavaScript to do it. See https://github.com/sul-dlss/earthworks/commit/958eaec9abdf9018c8a8e64573e9c73becb3d666

**Comment by dbrower** [comment]
The fields have been added to the solr schema. https://github.com/vecnet/deploy-dl/commit/9ce2eb76bc8a594b66ff94159e0573523a9112d2

**Comment by stevenvandervalk** [comment]
Thanks.  Added in a first draft of this in 5558bc8cbddad1731f3149c7eaa57f1a2b64867e
