### ISSUE TITLE
Mixed content warning

### ISSUE THREAD

**Issue by dbrower** [vecnet/dl-discovery#44]
On dl-dev.vecnet.org I get a mixed-content warning from my browser (both ff developer edition and chrome). This means some content was transmitted using un-encrypted http. I think that content is the map tiles.

Is it possible to fix this, and use a https connection to get them?

**Comment by stevenvandervalk** [comment]
The map tiles are now using https://github.com/leaflet-extras/leaflet-providers which defaults to // and https if the provider supports them.  Not sure that will fix the issue but the tile call will be https now if it can.

**Comment by stevenvandervalk** [comment]
Ok, I guess we can try a different fix - 4ce548f566dbc321abcc8a21f8d10173ec886371. Needs qa testing.
