### ISSUE TITLE
Potential improvements to meta data and search interface from user

### ISSUE THREAD

**Issue by stevenvandervalk** [vecnet/dl-discovery#45]
After speaking with Tanya Russell a few items that might be wish list or make their way in as good features for Digital Library users and librarians. 
- [ ] Ability to filter or search within modals ( e.g. huge list of authors, with only pagination can't get to M )
- [x] Information about citations in the meta data ( either input or output )

**Comment by dbrower** [comment]
Could you expand on the kind of information about citations in mind?

**Comment by stevenvandervalk** [comment]
Tanya and Susan mentioned the Malaria citation format or something similar that they see in Google Scholar. I don't know much about this but it was interesting.

**Comment by stevenvandervalk** [comment]
After reading Natalie's issue https://github.com/vecnet/dl-discovery/issues/54, perhaps I've misunderstood - as that seems to be a citation....

**Comment by stevenvandervalk** [comment]
Should read the documentation before I output.  This is `dc_bibliographic_citation_s`.
