### ISSUE TITLE
Search result pagination resets map

### ISSUE THREAD

**Issue by dbrower** [vecnet/dl-discovery#46]
From https://dl-dev.vecnet.org search for `Malaria` with the map "on". Then move to the next page by clicking "Next »". The map will reset to the narrow band on the left hand side AND the show map toggle is still "on".

**Comment by stevenvandervalk** [comment]
Thanks, wasn't altering hrefs to include the showmap=on param in the page when the user was toggling the map.  Fixed by 64380a429bca6144da83df653f8e82e45b77cd91 on the feature branch not yet merged.
