### ISSUE TITLE
A HREF for URL in record view is incorrect for displayed string - need to fix "URL"

### ISSUE THREAD

**Issue by nkmeyers** [vecnet/dl-discovery#47]
The A HREF value for URL in record view is not the same as displayed text string (for simulations at least) but the A HREF value in the "More details section" is good. 

Fix the first instance, determine if URL needs to be repeated as here?

```
<dt>URL</dt>
<dd><a href="/catalog/2658">https://ci-qa.vecnet.org/ts_emod/simulation/details/run/2658/</a></dd>

<!--TODO: Fish out the correct links from JSON object here || Check with Don -->
  <dt>More details at</dt>
  <dd itemprop="url"><a href="https://ci-qa.vecnet.org/ts_emod/simulation/details/run/2658/">https://ci-qa.vecnet.org/ts_emod/simulation/details/run/2658/</a></dd>
```

![image](https://cloud.githubusercontent.com/assets/3044754/7503528/96759c48-f411-11e4-945e-e5e8fc950e0c.png)

**Comment by stevenvandervalk** [comment]
Field names and values will reflect the data dictionary :  https://docs.google.com/document/d/1-lL3JakA5MQUrn8PqMoI1k_4McefUBF0G4R0wQoD_Po/edit#.

Let me know if you prefer different naming or urls.

By 4a2243f6b20b429b6c14a48207014af71695cabf.  Not in qa-deploy yet but shortly.

**Comment by stevenvandervalk** [comment]
Local URLs like /catalog/<id> could be because they are empty in the hash so should check for empty first before adding to page DD.

**Comment by stevenvandervalk** [comment]
Ok fixed in feature branch to be merged later today.
