### ISSUE TITLE
Retain all Sort by Options 

### ISSUE THREAD

**Issue by nkmeyers** [vecnet/dl-discovery#48]
Can we retain all the sort by options in the discovery UI?

They are showing as:
relevance, publisher, title

can you restore/implement the date sort options and the ascending/descending options we had previously?  We want to avoid losing any functionality
Can we still have:
publish date (asc or desc)
Title (asc or desc)
Date Uploaded(asc or desc)
Date modified (asc or desc)

![image](https://cloud.githubusercontent.com/assets/3044754/7503732/d8334ddc-f412-11e4-9791-8f305ad38e8f.png)

**Comment by dbrower** [comment]
@stevenvandervalk I think I got most of the sort fields into solr. If I missed any let me know.

**Comment by stevenvandervalk** [comment]
@dbrower  Ok I haven't meddled much in the solr config in rails but I would :

add e.g.  `config.add_sort_field 'dc_date_uploaded_dt_sort asc', :label => 'Date Uploaded'  Asc`

to `catalog_controller`.

for each of these options.

**Comment by stevenvandervalk** [comment]
@dbrower So should I go ahead and edit `schema.xml` 

and add fields to it such as below? Or is that something you should handle elsewhere? 

```
<!-- for sorting text fields -->
  <copyField source="dct_provenance_s"   dest="dct_provenance_sort"/>
  <copyField source="dc_publisher_s"     dest="dc_publisher_sort"/>
  <copyField source="dc_title_s"         dest="dc_title_sort"/>
```

**Comment by dbrower** [comment]
Yes, feel free to update it. The file is `roles/solr/files/schema.xml` in the deploy repo.

As far as I know, we are not using the `dct_provenance_s` field. It is (or should be) blank.
Also, the journal might be more interesting than the publisher (it is `dc_source_s`).

**Comment by stevenvandervalk** [comment]
@dbrower Ok based on the previous sorts, the schema and controller code has been added.  It seems to perform the correct solr query on vagrant but would like to add to our chat.

**Comment by stevenvandervalk** [comment]
https://github.com/projectblacklight/blacklight/wiki/Configuration---Solr-fields#sort-fields reminder in case the current implementation isn't correct.

**Comment by stevenvandervalk** [comment]
@nkmeyers I'm tempted to add icon and tags to show these values next to the thumbnail if people are sorting by them....?

**Comment by nkmeyers** [comment]
@steven - that'd be awesome - pls go ahead if you have time - great idea

Natalie Meyers
Typos by iPhone

On Jun 4, 2015, at 3:10 AM, Steve Vandervalk notifications@github.com
wrote:

@nkmeyers https://github.com/nkmeyers I'm tempted to add icon and tags to
show these values next to the thumbnail if people are sorting by them....?
