### ISSUE TITLE
search by map area doesnt? limit results

### ISSUE THREAD

**Issue by nkmeyers** [vecnet/dl-discovery#49]
Should search by map are limit results? it doesn't seem to ? Just seems to only display hits on that part of map rather than filter or inform the search & number of results?

For example if I search on term bendiocarb w/only  americas displayed and click search by map  I still get 127 results even though only 8 are from South america?

 how should non-locational records be filtered (included in results set) & counted when searching by map? 

![image](https://cloud.githubusercontent.com/assets/3044754/7503874/a4835e2c-f413-11e4-87a3-5bcefda1a690.png)

**Comment by stevenvandervalk** [comment]
Yep definitely buggy.  In local and remote testing prior, the map search filtered results as you would expect. Will debug.

**Comment by stevenvandervalk** [comment]
@dbrower This is confusing.  Rails + Solr is no longer limiting searches at all when we pass them a bbox param that is formatted how geoblacklight want.  Did a relevant SOLR change happen that I missed somewhere? because this works as is in previous commits and tagged versions.

**Comment by dbrower** [comment]
Possibilities are 1) there is an error in the solr schema, 2) geoblacklight changed how it relates to the bbox data and how it queries solr...I know that they were deprecating the bbox field in favor of something else.

**Comment by stevenvandervalk** [comment]
Ok.  I've written the question to the geobl group and hopefully my attempt at outreach is more successful this time.  I notice Earthworks now has  https://github.com/sul-dlss/earthworks/blob/master/app/controllers/catalog_controller.rb#L34 that we don't but following their threads didn't reveal anything.

**Comment by dbrower** [comment]
It looks like the setting `GEOMETRY_FIELD` is not set.

**Comment by stevenvandervalk** [comment]
Works here as well. Good to know that settings files don't inherit!
