### ISSUE TITLE
Change label text for Regions to Location(s) or Place Name(s) 

### ISSUE THREAD

**Issue by nkmeyers** [vecnet/dl-discovery#50]
Can we Change label text for "Regions" to Location Name(s) or Place Name(s) ?
![image](https://cloud.githubusercontent.com/assets/3044754/7503964/546d7d22-f414-11e4-8236-acf5c4647a78.png)

**Comment by stevenvandervalk** [comment]
Yup. b0476a72646b4bb42e2900f1b8bdcd26098f0a0e
