### ISSUE TITLE
add identifier field to record display

### ISSUE THREAD

**Issue by nkmeyers** [vecnet/dl-discovery#51]
We need to add identifier field to record display

For example, for this record (https://dl-dev.vecnet.org/catalog/d217qs56v) we need to get the content below to display somewhere, which tab or on main pane?

![image](https://cloud.githubusercontent.com/assets/3044754/7504084/63b5d83c-f415-11e4-8b38-820645cd3980.png)

**Comment by stevenvandervalk** [comment]
Added to the 'Record Information' tab for now  - 9e7b77d62d1f879d1def576c9aede3da34bcdb6a.  Let me know if should move.

**Comment by stevenvandervalk** [comment]
Added 
![screenshot 2015-05-19 14 53 07](https://cloud.githubusercontent.com/assets/3012945/7695699/c83d5ad4-fe36-11e4-998b-d8b03fd213db.png)
