### ISSUE TITLE
Add Advanced Search Option back to UI

### ISSUE THREAD

**Issue by nkmeyers** [vecnet/dl-discovery#53]
Need to Add Advanced Search Option back to UI (this option searches full text of pdfs as well as the regular indexes). 

The UI element could be just the checkbox maybe ?  is there such an input element as a checkbox "inside" the search box at the far right w/a label? 

![image](https://cloud.githubusercontent.com/assets/3044754/7506110/aa09cb40-f429-11e4-82d1-2ce23b0cd2e1.png)

**Comment by stevenvandervalk** [comment]
@dbrower Added the UI element but not sure what is the correct param to pass to enable full-text and citation search?.

https://github.com/vecnet/vecnet-dl/blob/66fa300b206f93941ca473e56602673c7362254f/app/controllers/catalog_controller.rb

Suggests $qf_full_text_citation and the dl currently passes full_text_citation=1

**Comment by stevenvandervalk** [comment]
After looking we think perhaps using a search_helper to add a local_param that is parsed to include the full text field.  See example at https://github.com/projectblacklight/blacklight_range_limit/blob/master/lib/blacklight_range_limit/controller_override.rb

**Comment by dbrower** [comment]
Lets check with Natalie about always enabling full text search for now.

**Comment by nkmeyers** [comment]
Best way to implement it is an option to "expand search" to include
full-text rather than w default to include full text - there should be two
index alternatives to point the search toward  depending on the user's
selection (maybe three including simulations ) .

Natalie Meyers
Typos by iPhone

On Jun 3, 2015, at 8:01 AM, Don Brower notifications@github.com wrote:

Lets check with Natalie about always enabling full text search for now.

**Comment by dbrower** [comment]
I thought @nkmeyers would argue for the need of keeping two types of search.

Devils advocate, why not do full text search by default? We would boost hits on titles, subjects, etc so that they would score higher than a hit in the full text. This promotes discover-ability over what we currently have, where people have an awkward interface to EXPAND their search. I don't have numbers, but I'm willing to wager no one uses full text search. Additionally, then an advanced search page, should one be added, would be used to NARROW the search.

As to the other point, there is not a third index for simulations. To search simulations only, one must facet on the resource type.

**Comment by dbrower** [comment]
Also, I should add, I'm up for doing whatever Natalie wants :)

**Comment by nkmeyers** [comment]
@devil'sadvocate / ok let's goahead w fulltext included as default search -
 lmk the boost order & weights

Natalie Meyers
Typos by iPhone

On Jun 3, 2015, at 10:24 AM, Don Brower notifications@github.com wrote:

I thought @nkmeyers https://github.com/nkmeyers would argue for the need
of keeping two types of search.

Devils advocate, why not do full text search by default? We would boost
hits on titles, subjects, etc so that they would score higher than a hit in
the full text. This promotes discover-ability over what we currently have,
where people have an awkward interface to EXPAND their search. I don't have
numbers, but I'm willing to wager no one uses full text search.
Additionally, then an advanced search page, should one be added, would be
used to NARROW the search.

As to the other point, there is not a third index for simulations. To
search simulations only, one must facet on the resource type.

**Comment by nkmeyers** [comment]
regarding boost order etc. Why do I care how we boost? 
This post says it all:
http://www.enterprisesearchblog.com/2015/01/your-enterprise-search-is-like-your-teenager.html

Hope it gives you a laugh or two. 

Natalie
