### ISSUE TITLE
adding author and citation info to hit list display

### ISSUE THREAD

**Issue by nkmeyers** [vecnet/dl-discovery#54]
Can we add the author and citation info back to hit list display before abstract? so sequence is title, then author, then citation, then abstract(if any)

![image](https://cloud.githubusercontent.com/assets/3044754/7506750/205c13b8-f432-11e4-9abf-73d0cd499cd6.png)

**Comment by stevenvandervalk** [comment]
Added dc_creator_sm and dc_bibliographic_citation_s to above the description text. These likely will need further formatting depending on the text size like the keyword tags.  I'm hoping to get around to that soon when I have a local copy of the remote solr to quickly test edge cases.  1ab03dc2d6cc57e41191708dfe1ec8e52585e5d6

@nkmeyers I really like your annotation drawings here Natalie, if I may say so :)

**Comment by stevenvandervalk** [comment]
Added to qa-deploy
![screenshot 2015-05-19 14 47 52](https://cloud.githubusercontent.com/assets/3012945/7695684/876d4032-fe36-11e4-8a53-1219f630a11d.png)
