### ISSUE TITLE
map wraps and drops

### ISSUE THREAD

**Issue by nkmeyers** [vecnet/dl-discovery#61]
if an item has spatial metadata that crosses hemisphere weird stuff still happens .

Can we stop map from dropping? Can we stop map from patterning and repeating ? 

Novaluron is an example of a chemical search that brings up records that causes this behavior

![image](https://cloud.githubusercontent.com/assets/3044754/7847996/d526c2e8-0495-11e5-84b2-17b7723cf3a1.png)

**Comment by stevenvandervalk** [comment]
Yes turned off the map repeating so its a single world map now.  Might be worth a group discussion incl @DanielBaird.

The crossing the hemisphere was a common complicated issue and we discussed and tried to deal with in https://github.com/vecnet/dl-discovery/issues/12
