### ISSUE TITLE
format display of time period of content 

### ISSUE THREAD

**Issue by nkmeyers** [vecnet/dl-discovery#68]
can time period of content display be formatted so brackets and quotes don't appear?

![image](https://cloud.githubusercontent.com/assets/3044754/7993719/0fcd3eea-0ad6-11e5-897e-cfa43e14f577.png)

**Comment by stevenvandervalk** [comment]
Yep  well spotted! 
done by f11e5b6cb398ac310d640837f7476350f2573515
