### ISSUE TITLE
add Prev Next at bottom of hitlist so user doesn't have to scroll to top to go to next page?

### ISSUE THREAD

**Issue by nkmeyers** [vecnet/dl-discovery#69]
Can we add add Prev Next at bottom of hitlist?
![image](https://cloud.githubusercontent.com/assets/3044754/7993748/46838336-0ad6-11e5-9538-c1ad06b45a65.png)

old one looked like this:

![image](https://cloud.githubusercontent.com/assets/3044754/7993756/5ea9c132-0ad6-11e5-97c1-05d6448db2fa.png)

**Comment by stevenvandervalk** [comment]
Sure. Implemented by f67fe42e6dd7925894ee625bf96ddf66e514d854.

**Comment by nkmeyers** [comment]
Excellent ! This'll save me some scrolling !

Natalie Meyers
Typos by iPhone

On Jun 8, 2015, at 8:45 PM, Steve Vandervalk notifications@github.com
wrote:

Sure. Implemented by f67fe42
https://github.com/vecnet/dl-discovery/commit/f67fe42e6dd7925894ee625bf96ddf66e514d854
.
