### ISSUE TITLE
Record display features

### ISSUE THREAD

**Issue by nkmeyers** [vecnet/dl-discovery#70]
Can we add download link and thumbnail display at record display level on top left? So user will see thumbnail and clicking it or text below will take user to to download similar to current behavior at dl.vecnet.org record display?

Can we add zebra striping back between fields on record display? 

Can we have a one-line label displayed eg "Links" instead of "Acess URL Links"  on record display view?
Make the URLS displayed for "Access URL LInks" actually hotlinked. Right now they are displaying only as strings are not active links. 

![image](https://cloud.githubusercontent.com/assets/3044754/7993881/4b190f96-0ad7-11e5-94de-354095cd968c.png)

![image](https://cloud.githubusercontent.com/assets/3044754/7994010/321b5386-0ad8-11e5-8eb0-7e3c7ec65817.png)

on our old system this record displays like: 
![image](https://cloud.githubusercontent.com/assets/3044754/7994022/40d76388-0ad8-11e5-89be-181f036522de.png)

**Comment by stevenvandervalk** [comment]
Ok I've tried to address each point. This rebase was being done on minimal sleep so will check it again tomorrow.
1. Thumbnail with download url (that doesn't always seem to exist?) b8003883fd27b070c9e4978c2038c09004f6cbdb
2. Zebra striping to record metadata summary b8003883fd27b070c9e4978c2038c09004f6cbdb
3. One line for links and active urls. 6f4f993
4. Identifier on multi line.... e9e3c87
