### ISSUE TITLE
Add 401, 403 error handler

### ISSUE THREAD

**Issue by dbrower** [vecnet/dl-discovery#77]
If there is no `current_user` it should offer a button to take the user to the log in page (similar to how the production app works).

**Comment by dbrower** [comment]
Need a `rescue_from` for the exception raised here: https://github.com/vecnet/dl-discovery/blob/qa-deploy/app/constraints/show_access_controls.rb#L20

Maybe change the name of the exception?

**Comment by stevenvandervalk** [comment]
Can handle the :access_denied exception in controller but perhaps you want something more like this https://github.com/richpeck/exception_handler?

Or just edit the 401 403 500 html pages to match the layout plus text in existing DL? (Currently uses a generator though...)

**Comment by stevenvandervalk** [comment]
Added a `rescue_from` handle to redirect to `root_url` from canonical Blacklight. a55d0efde259bd53110e0918a9f3b5be17dffae3

edited the plain html `public/` error pages to fit in and added the shared header. 1164f975d9dddfedc7e8c7ba0d88fa1f893a75d1
