### ISSUE TITLE
Add an js intro or tutorial to the start of page load

### ISSUE THREAD

**Issue by stevenvandervalk** [vecnet/dl-discovery#80]
due to some user confusion perhaps that would be brief and  helpful
like 
http://blog.tommoor.com/crumble/ 
or
https://usablica.github.io/intro.js/

**Comment by dbrower** [comment]
I am, at best, lukewarm to the idea.

**Comment by stevenvandervalk** [comment]
Ok, will revisit it if necessary later.
On 18 Jun 2015, at 4:54 am, Don Brower <notifications@github.com<mailto:notifications@github.com>> wrote:

I am, at best, lukewarm to the idea.
