### ISSUE TITLE
changing Records per page turns map display off and then autozoom freaks out

### ISSUE THREAD

**Issue by nkmeyers** [vecnet/dl-discovery#85]
changing Records per page turns map off (blue line) and then if you turn it back on autozoom (Red line)  freaks out 
![perpagebugcapture](https://cloud.githubusercontent.com/assets/3044754/8241219/17f64304-15d6-11e5-8a88-68e9a3f25d81.JPG)

**Comment by nkmeyers** [comment]
if I want to see all 28 records for novaluron in the map display and in the hit list and I use the per page element to select "50 per page" then after 50 are selected map display turns off, 50 paint to hit list, user can turn map display back on but then autozoom freaks out and map shrinks to only occupy part of screen  - this happened in demo we did  to Tom Burkot

**Comment by stevenvandervalk** [comment]
Sorry to hear that!  Yep I agree that is not correct behaviour.  I can't reproduce this on my dev branch so I'll have another look at this behaviour on monday or tuesday.
