### ISSUE TITLE
point count no longer displays? 

### ISSUE THREAD

**Issue by nkmeyers** [vecnet/dl-discovery#86]
I think the point count that was displayed in the ratio of points:records no longer displays? 

See stuff in green circle . . . for this search result set  should it show "21 Points from 28 records . . . "  instead of "points from 28 records"? 

search was "Novaluron", records per page set to 50  . . .

**Comment by nkmeyers** [comment]
![perpagebugcapture](https://cloud.githubusercontent.com/assets/3044754/8241686/d52aa756-15d8-11e5-8782-1bc1a4a31f07.JPG)

**Comment by nkmeyers** [comment]
![perpagebugcapture](https://cloud.githubusercontent.com/assets/3044754/8241697/e164a6fc-15d8-11e5-8286-023d10210e25.JPG)

**Comment by nkmeyers** [comment]
![28recordshowmanypointsannotation](https://cloud.githubusercontent.com/assets/3044754/8241810/7287c2ea-15d9-11e5-981a-5fdb7b423bf7.jpg)

**Comment by nkmeyers** [comment]
![28recordshowmanypointsannotation](https://cloud.githubusercontent.com/assets/3044754/8241871/ca33cd86-15d9-11e5-9e38-0011c48e78de.jpg)

**Comment by nkmeyers** [comment]
![28recordshowmanypointsannotation](https://cloud.githubusercontent.com/assets/3044754/8241885/d8287b12-15d9-11e5-92bb-d48ef5a4b29f.jpg)

**Comment by nkmeyers** [comment]
![pointsratiobugcaptureannotation](https://cloud.githubusercontent.com/assets/3044754/8241901/f759f6a0-15d9-11e5-9954-f1f4802f92cc.jpg)

**Comment by stevenvandervalk** [comment]
Done 14945ed3e9dd7e413fe9b813614d20459b3e499f
