### ISSUE TITLE
Facet test data

### ISSUE THREAD

**Issue by dbrower** [vecnet/dl-discovery#91]
The solr test data in the repository doesn't have hierarchal facet fields. Generate new data which does have them.

**Comment by dbrower** [comment]
done with d2140d77cd74e9810eef66b3547f1c322b18f91a

**Comment by stevenvandervalk** [comment]
@dbrower  In vagrant I source and turn on chruby in order to run the upload_script.rb.

Then with the new data I ran into 

```
 ./script/upload-to-solr.rb vecnet-solr-sample.json http://localhost:8983/solr/discovery
Source is file vecnet-solr-sample.json
Target is http://localhost:8983/solr/discovery
Uploading record vecnet:6w924p532
/home/vagrant/.gem/ruby/2.0.0/gems/rsolr-1.0.12/lib/rsolr/client.rb:284:in `adapt_response': RSolr::Error::Http - 409 Conflict (RSolr::Error::Http)
Error: {'responseHeader'=>{'status'=>409,'QTime'=>2},'error'=>{'msg'=>'version conflict for vecnet:6w924p532 expected=1504978690020212700 actual=-1','code'=>409}}
```

Any ideas?  I'm guessing you don't see this.  I tried clearing the solr core first as well.  Should you/I replace the `vn_content_version_s`?

**Comment by stevenvandervalk** [comment]
I found 

https://stackoverflow.com/questions/25914447/solr-optimistic-concurrency-update-version-conflict 
https://cwiki.apache.org/confluence/display/solr/Updating+Parts+of+Documents

and hacked a few things with deleting `_version_` but no luck.
